//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logging
    {
        public int LoggingID { get; set; }
        public string LoggingLevel { get; set; }
        public Nullable<System.DateTime> LoggingDate { get; set; }
        public string LoggingMessage { get; set; }
        public string LoggingUnameMac { get; set; }
        public string LoggingMacname { get; set; }
        public string LoggingUnameApp { get; set; }
    }
}
