//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sati
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sati()
        {
            this.SatisTotals = new HashSet<SatisTotal>();
        }
    
        public int SatisID { get; set; }
        public int SatisPerID { get; set; }
        public int SatisMusID { get; set; }
        public Nullable<System.DateTime> SatisTarih { get; set; }
        public decimal SatisFiyat { get; set; }
        public int SatisAdet { get; set; }
        public int SatisUrunID { get; set; }
    
        public virtual Musteri Musteri { get; set; }
        public virtual Personel Personel { get; set; }
        public virtual Urun Urun { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatisTotal> SatisTotals { get; set; }
    }
}
