//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SDB : DbContext
    {
        public SDB()
            : base("name=SDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kategori> Kategoris { get; set; }
        public virtual DbSet<Musteri> Musteris { get; set; }
        public virtual DbSet<Personel> Personels { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Sati> Satis { get; set; }
        public virtual DbSet<SatisTotal> SatisTotals { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Urun> Uruns { get; set; }
        public virtual DbSet<Logging> Loggings { get; set; }
    }
}
